routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('candidates', 'CandidatesController')->middleware('auth');
Route::get('candidates/changeuser/{cid}/{uid?}', 'CandidatesController@changeUser')->name('candidate.changeuser');
Route::get('candidates/changestatus/{cid}/{sid}', 'CandidatesController@changeStatus')->name('candidates.changestatus')->middleware('auth');

Route::get('mycandidates', 'CandidatesController@myCandidates')->name('candidates.mycandidates')->middleware('auth');



Route::get('candidates/delete/{id}', 'CandidatesController@destroy')->name('candidate.delete');


Route::resource('interviews', 'InterviewsController')->middleware('auth');
Route::get('show', 'InterviewsController@show')->name('interviews.show');
Route::get('myinterviews', 'InterviewsController@myInterviews')->name('interviews.myinterviews')->middleware('auth');
// Route::get('interviews/selectcandidate/{iid}/{cid?}', 'InterviewsController@selectcandidate')->name('interviews.selectcandidate');


Route::get('/hello', function (){
    return 'Hello Larevel';
}); 

Route::get('/student/{id}', function ($id  = 'No student found'){
    return 'We got student with id '.$id;
});

Route::get('/car/{id?}', function ($id  = null){
    if(isset($id)){
        //TODO: validate for integer  
        return "We got car $id";
    } else {
        return 'We need the id to find your car';
    }
});


Route::get('/comment/{id}', function ($id) {
    return view('comment', compact('id'));
});

Route::get('/users/{email}/{name?}', function ($email,$name = null) {
    if(!isset($name)){
        $name = 'Mising name';
    }
    return view('users', compact('email','name'));
});




#example
Route::get('/users1/{name?}/{email}', function ($name = null, $email) {
    if(!isset($name)){
        $name = 'Mising name';
    }
    return view('users', compact('email','name'));
});























Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/InterviewsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Interviews;
use App\Candidate;
use App\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;

class InterviewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    public function myInterviews()
    {        
        $userId = Auth::id();
        $user = User::findOrFail($userId);
        $interviews = $user->interviews;
        //$candidates = Candidate::all();
        $users = User::all();
        // $statuses = Status::all();        
        return view('interviews.show', compact('interviews','users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        Gate::authorize('assign-user');
        Gate::authorize('add-interview');
        $users = User::all();
        $candidates = Candidate::all();
        $interviews = Interviews::all();
        return view('interviews.create', compact('interviews','candidates', 'users'));
    }

    // public function selectcandidate(Request $request){
    //     $iid = $request->id;
    //     $cid = $request->candidate_id;
    //     $interviews = Interviews::findOrFail($iid);
    //     $interviews->save();
    //     return redirect('candidates');
    // }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $interview = new Interviews();
        $inter = $interview->create($request->all());
        $inter->candidate_id = $request->candidate_id; 
        $inter->user_id = $request->user_id;
        $inter->save();
        return redirect('candidates');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
        $candidates = Candidate::all();
        $interviews = Interviews::all();
        return view('interviews.show', compact('interviews', 'candidates'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/interviews/create.blade.php
@extends('layouts.app')

@section('title', 'Create interview')

@section('content')
        <h1>Create interview</h1>
        <form method = "post" action = "{{action('InterviewsController@store')}}">
        @csrf 
        <div class="form-group">
            <label for = "date">Date</label>
            <input type = "date" class="form-control" name = "date">
        </div>     
        <div class="form-group">
            <label for = "review">Review</label>
            <input type = "text" class="form-control" name = "review">
        </div> 
      
        @foreach ($interviews as $interview)
        <form method="POST" action="{{ route('interviews.store',[$interview->id]) }}">
        @endforeach     
                    @csrf  
                    <div class="form-group row">
                   
                    <div class="col-md-6">
                        <select class="form-control" name="candidate_id">                                                                         
                        
                          @foreach ($candidates as $candidate)
                          <option value="{{ $candidate->id }}"> 
                              {{ $candidate->name }} 
                          </option>
                          @endforeach 
                           
                        </select>
                    </div>
                    <input name="id" type="hidden" value = {{$candidate->id}} >
                                    
                </form> 

                <tr>
                @foreach ($interviews as $interview)
        <form method="POST" action="{{ route('interviews.store',[$interview->id]) }}">
        @endforeach     
                    @csrf  
                    <div class="form-group row">
                   
                    <div class="col-md-6">
                        <select class="form-control" name="user_id">                                                                         
                        
                          @foreach ($users as $user)
                          <option value="{{ $user->id }}"> 
                              {{ $user->name }} 
                          </option>
                          @endforeach 
                           
                        </select>
                    </div>
                    <input name="id" type="hidden" value = {{$user->id}} >
                    <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
    
                            </div>
                    </div>                    
                </form> 
                </tr>
                </tr> 
           <td>Created</td><td>{{$interview->created_at}}</td>
        </tr>
        <tr>
           <td>Updated</td><td>{{$interview->updated_at}}</td>  
        </tr>  
                <div>
            <input type = "submit" name = "submit" value = "Create candidate">
        </div> 
                </div>
 
@endsection

resources/views/interviews/show.blade.php
@extends('layouts.app')

@section('title', 'Interviews')

@section('content')
<!-- @if(Session::has('notallowed'))
<div class = 'alert alert-danger'>
    {{Session::get('notallowed')}}
</div>
@endif -->
<h1>Candidate interview</h1>
<table class = "table table-dark">
    <!-- the table data -->
    @foreach($interviews as $interview)
        <tr>
            <td>Id</td><td>{{$interview->id}}</td>
        </tr>
        <tr>
            <td>Date</td><td>{{$interview->date}}</td>
        </tr>
        <tr>
            <td>Review</td><td>{{$interview->review}}</td>
        </tr> 
        <tr>
            <td>Candidate</td><td>{{$interview->candidate_id}}</td>
        </tr> 
           <td>Created</td><td>{{$interview->created_at}}</td>
        </tr>
        <tr>
           <td>Updated</td><td>{{$interview->updated_at}}</td>  
        </tr>  
        @endforeach  
        </table>
@endsection